apiVersion: apps/v1
kind: Deployment
metadata:
  name: veggie-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veggie-node-app
  template:
    metadata:
     labels:
       app: veggie-node-app
    spec:
      initContainers:
          - name: run-migrations
            image: bysdudent/veggie-migration:lab2
            imagePullPolicy: Always
            command: ["./node_modules/.bin/node-pg-migrate", "up"] # CLI команда запуску міграцій, де $(POSTGRESQL_URL) і $(VERSION) змінні середовища
            env:
              - name: DATABASE_URL
                value: "postgres://demo:demo@postgres:5432/demo"
              - name: VERSION
                value: "20211128095755"     
      containers:
        - image: bysdudent/veggie-nodejs:lab2.1
          name: veggie-node-app
          ports:
            - containerPort: 3000 
          # for lab3 and further port changed to 8080
        
