nameOverride: history-service

image:
  dockerNamespace: bysdudent/
  name: history-service
  tag: lab5

migrations:
  image:
    dockerNamespace: bysdudent/
    name: history-migration
    tag: lab5
  config:
    DATABASE_URL: "postgres://demo:demo@postgres:5432/demo"

configs:
  POSTGRES_DB: demo
  POSTGRES_HOST: postgres

secrets:
  POSTGRES_USER: "ZGVtbw=="
  POSTGRES_PASSWORD: "ZGVtbw=="

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

ingress:
  path: /history
  port: http