image:
  dockerNamespace: bysdudent/
  name: fruit-service
  tag: lab3

service:
  ports:
    - name: http
      port: 80
      containerPort: 8080

migrations:
  image:
    dockerNamespace: bysdudent/
    name: orders-migration
    tag: lab2
  config:
    DATABASE_URL: "postgres://demo:demo@postgres:5432/demo"

configs:
  POSTGRES_DB: demo
  POSTGRES_HOST: postgres
  


secrets:
  POSTGRES_USER: "ZGVtbw=="
  POSTGRES_PASSWORD: "ZGVtbw=="

ingress:
  path: /orders
  port: http